name: Pipeline to Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Build to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
      
      - name: "Configure AWS Credentials" #Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::717279707647:role/Allow-GitHub_BuildToECR
          aws-region: sa-east-1
      
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Build Image, Tag and Push to ECR
        run: | 
          docker build -t devops-lab-site:v1.0 .
          docker tag devops-lab-site:v1.0 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0
          docker push 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0


      