name: Pipeline to Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Build to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
      
      - name: "Configure AWS Credentials" #Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::717279707647:role/Allow-GitHub_BuildToECR
          aws-region: sa-east-1
      
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Build Image, Tag and Push to ECR
        run: | 
          docker build -t devops-lab-site:v1.0 .
          docker tag devops-lab-site:v1.0 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0
          docker push 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0
  
  job2:
    name: Deploy to EC2
    env:
      DEVOPS_KEY: ${{secrets.DEVOPS_KEY}}
      PUBLIC_IP: ${{secrets.PUBLIC_IP}}
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Connect to EC2 SSH and Deploy #Alterar IP da mÃ¡quina no git
        run: | 
          echo "$DEVOPS_KEY" > devops-key.pem
          chmod 400 devops-key.pem
          ssh -o StrictHostKeyChecking=no -i devops-key.pem ec2-user@$PUBLIC_IP << 'EOF'
            aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 717279707647.dkr.ecr.sa-east-1.amazonaws.com
            docker pull 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0
            docker stop devopslab_site || true
            docker rm devopslab_site || true
            docker run -d --name devopslab_site -p 80:80 717279707647.dkr.ecr.sa-east-1.amazonaws.com/devopslab_container:v1.0
          EOF
          rm devops-key.pem
